### ISSUE TITLE
IP address resoultion problem

### ISSUE THREAD

**Issue by Mid3us** [azadrahorg/v2rayCaddy-vless-vmess-ws-tls#1]
Lines 235 - 242 didn't work, for some reason https://api.myip.la didn't return IPv4 address.

To solve it for my issue i applied ip=$(curl ifconfig.me) since i didn't need IPv6 Adressing.

Maybe use other source of IP addresses or verify curl commands for acquisition? 

Besides that its a great script, Cheers!

**Comment by azadrahorg** [comment]
Hello
The bug has been fixed
